create type "public"."waiver_event" as enum ('user_opened', 'user_signed');

drop policy "Allow participants to view their waiver signatures" on "public"."waiver_signatures";

revoke delete on table "public"."waiver_signatures" from "anon";

revoke insert on table "public"."waiver_signatures" from "anon";

revoke references on table "public"."waiver_signatures" from "anon";

revoke select on table "public"."waiver_signatures" from "anon";

revoke trigger on table "public"."waiver_signatures" from "anon";

revoke truncate on table "public"."waiver_signatures" from "anon";

revoke update on table "public"."waiver_signatures" from "anon";

revoke delete on table "public"."waiver_signatures" from "authenticated";

revoke insert on table "public"."waiver_signatures" from "authenticated";

revoke references on table "public"."waiver_signatures" from "authenticated";

revoke select on table "public"."waiver_signatures" from "authenticated";

revoke trigger on table "public"."waiver_signatures" from "authenticated";

revoke truncate on table "public"."waiver_signatures" from "authenticated";

revoke update on table "public"."waiver_signatures" from "authenticated";

revoke delete on table "public"."waiver_signatures" from "service_role";

revoke insert on table "public"."waiver_signatures" from "service_role";

revoke references on table "public"."waiver_signatures" from "service_role";

revoke select on table "public"."waiver_signatures" from "service_role";

revoke trigger on table "public"."waiver_signatures" from "service_role";

revoke truncate on table "public"."waiver_signatures" from "service_role";

revoke update on table "public"."waiver_signatures" from "service_role";

alter table "public"."participant_info" drop constraint "participant_info_usc_id_key";

alter table "public"."tickets" drop constraint "tickets_waiver_id_fkey";

alter table "public"."waiver_signatures" drop constraint "waiver_signatures_user_id_fkey";

alter table "public"."participant_info" drop constraint "participant_info_usc_id_check";

alter table "public"."waiver_signatures" drop constraint "waiver_signatures_pkey";

drop index if exists "public"."participant_info_usc_id_key";

drop index if exists "public"."waiver_signatures_pkey";

drop table "public"."waiver_signatures";


  create table "public"."trip_waivers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "trip_id" uuid not null,
    "content" text not null,
    "type" public.ticket_type not null,
    "template_id" uuid not null
      );


alter table "public"."trip_waivers" enable row level security;


  create table "public"."waiver_events" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "event" public.waiver_event not null,
    "user_id" uuid not null,
    "trip_id" uuid not null,
    "ip_address" text not null,
    "user_agent" text not null default 'unknown'::text
      );


alter table "public"."waiver_events" enable row level security;


  create table "public"."waiver_templates" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "content" text not null,
    "type" public.ticket_type not null,
    "active" boolean not null default false
      );


alter table "public"."waiver_templates" enable row level security;

alter table "public"."participant_info" alter column "usc_id" set data type text using "usc_id"::text;

alter table "public"."tickets" drop column "waiver_id";

CREATE UNIQUE INDEX active_waiver_template_types ON public.waiver_templates USING btree (type) WHERE (active = true);

CREATE UNIQUE INDEX trip_ticket_type_unique ON public.trip_waivers USING btree (trip_id, type);

CREATE UNIQUE INDEX trip_waivers_pkey ON public.trip_waivers USING btree (id);

CREATE UNIQUE INDEX waiver_events_pkey ON public.waiver_events USING btree (id);

CREATE UNIQUE INDEX waiver_templates_pkey ON public.waiver_templates USING btree (id);

alter table "public"."trip_waivers" add constraint "trip_waivers_pkey" PRIMARY KEY using index "trip_waivers_pkey";

alter table "public"."waiver_events" add constraint "waiver_events_pkey" PRIMARY KEY using index "waiver_events_pkey";

alter table "public"."waiver_templates" add constraint "waiver_templates_pkey" PRIMARY KEY using index "waiver_templates_pkey";

alter table "public"."trip_waivers" add constraint "trip_ticket_type_unique" UNIQUE using index "trip_ticket_type_unique";

alter table "public"."trip_waivers" add constraint "trip_waivers_template_id_fkey" FOREIGN KEY (template_id) REFERENCES public.waiver_templates(id) not valid;

alter table "public"."trip_waivers" validate constraint "trip_waivers_template_id_fkey";

alter table "public"."trip_waivers" add constraint "trip_waivers_trip_id_fkey" FOREIGN KEY (trip_id) REFERENCES public.trips(id) not valid;

alter table "public"."trip_waivers" validate constraint "trip_waivers_trip_id_fkey";

alter table "public"."waiver_events" add constraint "waiver_events_trip_id_fkey" FOREIGN KEY (trip_id) REFERENCES public.trips(id) not valid;

alter table "public"."waiver_events" validate constraint "waiver_events_trip_id_fkey";

alter table "public"."waiver_events" add constraint "waiver_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."waiver_events" validate constraint "waiver_events_user_id_fkey";

alter table "public"."participant_info" add constraint "participant_info_usc_id_check" CHECK ((usc_id ~ '^\d{10}$'::text)) not valid;

alter table "public"."participant_info" validate constraint "participant_info_usc_id_check";

grant delete on table "public"."allowed_trip_participants" to "postgres";

grant insert on table "public"."allowed_trip_participants" to "postgres";

grant references on table "public"."allowed_trip_participants" to "postgres";

grant select on table "public"."allowed_trip_participants" to "postgres";

grant trigger on table "public"."allowed_trip_participants" to "postgres";

grant truncate on table "public"."allowed_trip_participants" to "postgres";

grant update on table "public"."allowed_trip_participants" to "postgres";

grant delete on table "public"."trip_waivers" to "anon";

grant insert on table "public"."trip_waivers" to "anon";

grant references on table "public"."trip_waivers" to "anon";

grant select on table "public"."trip_waivers" to "anon";

grant trigger on table "public"."trip_waivers" to "anon";

grant truncate on table "public"."trip_waivers" to "anon";

grant update on table "public"."trip_waivers" to "anon";

grant delete on table "public"."trip_waivers" to "authenticated";

grant insert on table "public"."trip_waivers" to "authenticated";

grant references on table "public"."trip_waivers" to "authenticated";

grant select on table "public"."trip_waivers" to "authenticated";

grant trigger on table "public"."trip_waivers" to "authenticated";

grant truncate on table "public"."trip_waivers" to "authenticated";

grant update on table "public"."trip_waivers" to "authenticated";

grant delete on table "public"."trip_waivers" to "postgres";

grant insert on table "public"."trip_waivers" to "postgres";

grant references on table "public"."trip_waivers" to "postgres";

grant select on table "public"."trip_waivers" to "postgres";

grant trigger on table "public"."trip_waivers" to "postgres";

grant truncate on table "public"."trip_waivers" to "postgres";

grant update on table "public"."trip_waivers" to "postgres";

grant delete on table "public"."trip_waivers" to "service_role";

grant insert on table "public"."trip_waivers" to "service_role";

grant references on table "public"."trip_waivers" to "service_role";

grant select on table "public"."trip_waivers" to "service_role";

grant trigger on table "public"."trip_waivers" to "service_role";

grant truncate on table "public"."trip_waivers" to "service_role";

grant update on table "public"."trip_waivers" to "service_role";

grant delete on table "public"."waiver_events" to "anon";

grant insert on table "public"."waiver_events" to "anon";

grant references on table "public"."waiver_events" to "anon";

grant select on table "public"."waiver_events" to "anon";

grant trigger on table "public"."waiver_events" to "anon";

grant truncate on table "public"."waiver_events" to "anon";

grant update on table "public"."waiver_events" to "anon";

grant delete on table "public"."waiver_events" to "authenticated";

grant insert on table "public"."waiver_events" to "authenticated";

grant references on table "public"."waiver_events" to "authenticated";

grant select on table "public"."waiver_events" to "authenticated";

grant trigger on table "public"."waiver_events" to "authenticated";

grant truncate on table "public"."waiver_events" to "authenticated";

grant update on table "public"."waiver_events" to "authenticated";

grant delete on table "public"."waiver_events" to "postgres";

grant insert on table "public"."waiver_events" to "postgres";

grant references on table "public"."waiver_events" to "postgres";

grant select on table "public"."waiver_events" to "postgres";

grant trigger on table "public"."waiver_events" to "postgres";

grant truncate on table "public"."waiver_events" to "postgres";

grant update on table "public"."waiver_events" to "postgres";

grant delete on table "public"."waiver_events" to "service_role";

grant insert on table "public"."waiver_events" to "service_role";

grant references on table "public"."waiver_events" to "service_role";

grant select on table "public"."waiver_events" to "service_role";

grant trigger on table "public"."waiver_events" to "service_role";

grant truncate on table "public"."waiver_events" to "service_role";

grant update on table "public"."waiver_events" to "service_role";

grant delete on table "public"."waiver_templates" to "anon";

grant insert on table "public"."waiver_templates" to "anon";

grant references on table "public"."waiver_templates" to "anon";

grant select on table "public"."waiver_templates" to "anon";

grant trigger on table "public"."waiver_templates" to "anon";

grant truncate on table "public"."waiver_templates" to "anon";

grant update on table "public"."waiver_templates" to "anon";

grant delete on table "public"."waiver_templates" to "authenticated";

grant insert on table "public"."waiver_templates" to "authenticated";

grant references on table "public"."waiver_templates" to "authenticated";

grant select on table "public"."waiver_templates" to "authenticated";

grant trigger on table "public"."waiver_templates" to "authenticated";

grant truncate on table "public"."waiver_templates" to "authenticated";

grant update on table "public"."waiver_templates" to "authenticated";

grant delete on table "public"."waiver_templates" to "postgres";

grant insert on table "public"."waiver_templates" to "postgres";

grant references on table "public"."waiver_templates" to "postgres";

grant select on table "public"."waiver_templates" to "postgres";

grant trigger on table "public"."waiver_templates" to "postgres";

grant truncate on table "public"."waiver_templates" to "postgres";

grant update on table "public"."waiver_templates" to "postgres";

grant delete on table "public"."waiver_templates" to "service_role";

grant insert on table "public"."waiver_templates" to "service_role";

grant references on table "public"."waiver_templates" to "service_role";

grant select on table "public"."waiver_templates" to "service_role";

grant trigger on table "public"."waiver_templates" to "service_role";

grant truncate on table "public"."waiver_templates" to "service_role";

grant update on table "public"."waiver_templates" to "service_role";


  create policy "Participants can insert their own information"
  on "public"."participant_info"
  as permissive
  for insert
  to authenticated
with check ((user_id = ( SELECT auth.uid() AS uid)));



  create policy "Participants can select their own information"
  on "public"."participant_info"
  as permissive
  for select
  to authenticated
using ((user_id = ( SELECT auth.uid() AS uid)));



  create policy "Participants can update their own information"
  on "public"."participant_info"
  as permissive
  for update
  to authenticated
using ((user_id = ( SELECT auth.uid() AS uid)))
with check ((user_id = ( SELECT auth.uid() AS uid)));



